name: davidgerber
favicon: null
layout_spectrum: 0.007861593971028924
typography_spectrum: 0.7478338112123311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.15919641219079494
  lightness: 0.1777741692494601
  saturation: 0.3422787026502192
  rhythmicContrast: 0.3474053789395839
purpose: []
